server:
  port: "8080"
  env: development
  enable_swagger: true

mongodb:
  uri: mongodb://admin:secret@localhost:27017
  database: learning_japanese

redis:
  addr: localhost:6379
  password: ""
  db: "0"

oauth:
  google_client_id: YOUR_GOOGLE_CLIENT_ID
  google_client_secret: YOUR_GOOGLE_CLIENT_SECRET
  redirect_url: http://localhost:8080/auth/google/callback
  jwt_secret: your-jwt-secret-change-in-production
