// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grpc_service/v1/search.proto

package searchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED ContentType = 0
	ContentType_CONTENT_TYPE_WORD        ContentType = 1
	ContentType_CONTENT_TYPE_GRAMMAR     ContentType = 2
	ContentType_CONTENT_TYPE_PARAGRAPH   ContentType = 3
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_WORD",
		2: "CONTENT_TYPE_GRAMMAR",
		3: "CONTENT_TYPE_PARAGRAPH",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED": 0,
		"CONTENT_TYPE_WORD":        1,
		"CONTENT_TYPE_GRAMMAR":     2,
		"CONTENT_TYPE_PARAGRAPH":   3,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_service_v1_search_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_grpc_service_v1_search_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{0}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          uint32                 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filter        *ContentFilter         `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetFilter() *ContentFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ContentFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentTypes  []ContentType          `protobuf:"varint,1,rep,packed,name=content_types,json=contentTypes,proto3,enum=grpc_service.v1.ContentType" json:"content_types,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentFilter) Reset() {
	*x = ContentFilter{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentFilter) ProtoMessage() {}

func (x *ContentFilter) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentFilter.ProtoReflect.Descriptor instead.
func (*ContentFilter) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *ContentFilter) GetContentTypes() []ContentType {
	if x != nil {
		return x.ContentTypes
	}
	return nil
}

func (x *ContentFilter) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	TotalHits     uint32                 `protobuf:"varint,2,opt,name=total_hits,json=totalHits,proto3" json:"total_hits,omitempty"`
	QueryTimeMs   float64                `protobuf:"fixed64,3,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetTotalHits() uint32 {
	if x != nil {
		return x.TotalHits
	}
	return 0
}

func (x *SearchResponse) GetQueryTimeMs() float64 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Snippet       string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	ContentType   ContentType            `protobuf:"varint,5,opt,name=content_type,json=contentType,proto3,enum=grpc_service.v1.ContentType" json:"content_type,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchHit) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *SearchHit) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *SearchHit) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{4}
}

type GetStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalDocuments    uint32                 `protobuf:"varint,1,opt,name=total_documents,json=totalDocuments,proto3" json:"total_documents,omitempty"`
	AvgDocumentLength float64                `protobuf:"fixed64,2,opt,name=avg_document_length,json=avgDocumentLength,proto3" json:"avg_document_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsResponse) GetTotalDocuments() uint32 {
	if x != nil {
		return x.TotalDocuments
	}
	return 0
}

func (x *GetStatsResponse) GetAvgDocumentLength() float64 {
	if x != nil {
		return x.AvgDocumentLength
	}
	return 0
}

type IndexDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ContentType   ContentType            `protobuf:"varint,5,opt,name=content_type,json=contentType,proto3,enum=grpc_service.v1.ContentType" json:"content_type,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentRequest) Reset() {
	*x = IndexDocumentRequest{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentRequest) ProtoMessage() {}

func (x *IndexDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentRequest.ProtoReflect.Descriptor instead.
func (*IndexDocumentRequest) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *IndexDocumentRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *IndexDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IndexDocumentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IndexDocumentRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *IndexDocumentRequest) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *IndexDocumentRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type IndexDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentResponse) Reset() {
	*x = IndexDocumentResponse{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentResponse) ProtoMessage() {}

func (x *IndexDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentResponse.ProtoReflect.Descriptor instead.
func (*IndexDocumentResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *IndexDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BulkIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexedCount  uint32                 `protobuf:"varint,1,opt,name=indexed_count,json=indexedCount,proto3" json:"indexed_count,omitempty"`
	FailedCount   uint32                 `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkIndexResponse) Reset() {
	*x = BulkIndexResponse{}
	mi := &file_grpc_service_v1_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkIndexResponse) ProtoMessage() {}

func (x *BulkIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_service_v1_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkIndexResponse.ProtoReflect.Descriptor instead.
func (*BulkIndexResponse) Descriptor() ([]byte, []int) {
	return file_grpc_service_v1_search_proto_rawDescGZIP(), []int{8}
}

func (x *BulkIndexResponse) GetIndexedCount() uint32 {
	if x != nil {
		return x.IndexedCount
	}
	return 0
}

func (x *BulkIndexResponse) GetFailedCount() uint32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

var File_grpc_service_v1_search_proto protoreflect.FileDescriptor

const file_grpc_service_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x1cgrpc_service/v1/search.proto\x12\x0fgrpc_service.v1\"r\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\rR\x04topK\x126\n" +
	"\x06filter\x18\x03 \x01(\v2\x1e.grpc_service.v1.ContentFilterR\x06filter\"h\n" +
	"\rContentFilter\x12A\n" +
	"\rcontent_types\x18\x01 \x03(\x0e2\x1c.grpc_service.v1.ContentTypeR\fcontentTypes\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\x83\x01\n" +
	"\x0eSearchResponse\x12.\n" +
	"\x04hits\x18\x01 \x03(\v2\x1a.grpc_service.v1.SearchHitR\x04hits\x12\x1d\n" +
	"\n" +
	"total_hits\x18\x02 \x01(\rR\ttotalHits\x12\"\n" +
	"\rquery_time_ms\x18\x03 \x01(\x01R\vqueryTimeMs\"\xbf\x01\n" +
	"\tSearchHit\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\x12?\n" +
	"\fcontent_type\x18\x05 \x01(\x0e2\x1c.grpc_service.v1.ContentTypeR\vcontentType\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\"\x11\n" +
	"\x0fGetStatsRequest\"k\n" +
	"\x10GetStatsResponse\x12'\n" +
	"\x0ftotal_documents\x18\x01 \x01(\rR\x0etotalDocuments\x12.\n" +
	"\x13avg_document_length\x18\x02 \x01(\x01R\x11avgDocumentLength\"\xc0\x01\n" +
	"\x14IndexDocumentRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12?\n" +
	"\fcontent_type\x18\x05 \x01(\x0e2\x1c.grpc_service.v1.ContentTypeR\vcontentType\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\"K\n" +
	"\x15IndexDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x11BulkIndexResponse\x12#\n" +
	"\rindexed_count\x18\x01 \x01(\rR\findexedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\rR\vfailedCount*x\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONTENT_TYPE_WORD\x10\x01\x12\x18\n" +
	"\x14CONTENT_TYPE_GRAMMAR\x10\x02\x12\x1a\n" +
	"\x16CONTENT_TYPE_PARAGRAPH\x10\x032\xe5\x02\n" +
	"\rSearchService\x12I\n" +
	"\x06Search\x12\x1e.grpc_service.v1.SearchRequest\x1a\x1f.grpc_service.v1.SearchResponse\x12O\n" +
	"\bGetStats\x12 .grpc_service.v1.GetStatsRequest\x1a!.grpc_service.v1.GetStatsResponse\x12^\n" +
	"\rIndexDocument\x12%.grpc_service.v1.IndexDocumentRequest\x1a&.grpc_service.v1.IndexDocumentResponse\x12X\n" +
	"\tBulkIndex\x12%.grpc_service.v1.IndexDocumentRequest\x1a\".grpc_service.v1.BulkIndexResponse(\x01BIZGgithub.com/Tranduy1dol/kotoba-press-core/proto/grpc_service/v1;searchpbb\x06proto3"

var (
	file_grpc_service_v1_search_proto_rawDescOnce sync.Once
	file_grpc_service_v1_search_proto_rawDescData []byte
)

func file_grpc_service_v1_search_proto_rawDescGZIP() []byte {
	file_grpc_service_v1_search_proto_rawDescOnce.Do(func() {
		file_grpc_service_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_service_v1_search_proto_rawDesc), len(file_grpc_service_v1_search_proto_rawDesc)))
	})
	return file_grpc_service_v1_search_proto_rawDescData
}

var file_grpc_service_v1_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_service_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_grpc_service_v1_search_proto_goTypes = []any{
	(ContentType)(0),              // 0: grpc_service.v1.ContentType
	(*SearchRequest)(nil),         // 1: grpc_service.v1.SearchRequest
	(*ContentFilter)(nil),         // 2: grpc_service.v1.ContentFilter
	(*SearchResponse)(nil),        // 3: grpc_service.v1.SearchResponse
	(*SearchHit)(nil),             // 4: grpc_service.v1.SearchHit
	(*GetStatsRequest)(nil),       // 5: grpc_service.v1.GetStatsRequest
	(*GetStatsResponse)(nil),      // 6: grpc_service.v1.GetStatsResponse
	(*IndexDocumentRequest)(nil),  // 7: grpc_service.v1.IndexDocumentRequest
	(*IndexDocumentResponse)(nil), // 8: grpc_service.v1.IndexDocumentResponse
	(*BulkIndexResponse)(nil),     // 9: grpc_service.v1.BulkIndexResponse
}
var file_grpc_service_v1_search_proto_depIdxs = []int32{
	2, // 0: grpc_service.v1.SearchRequest.filter:type_name -> grpc_service.v1.ContentFilter
	0, // 1: grpc_service.v1.ContentFilter.content_types:type_name -> grpc_service.v1.ContentType
	4, // 2: grpc_service.v1.SearchResponse.hits:type_name -> grpc_service.v1.SearchHit
	0, // 3: grpc_service.v1.SearchHit.content_type:type_name -> grpc_service.v1.ContentType
	0, // 4: grpc_service.v1.IndexDocumentRequest.content_type:type_name -> grpc_service.v1.ContentType
	1, // 5: grpc_service.v1.SearchService.Search:input_type -> grpc_service.v1.SearchRequest
	5, // 6: grpc_service.v1.SearchService.GetStats:input_type -> grpc_service.v1.GetStatsRequest
	7, // 7: grpc_service.v1.SearchService.IndexDocument:input_type -> grpc_service.v1.IndexDocumentRequest
	7, // 8: grpc_service.v1.SearchService.BulkIndex:input_type -> grpc_service.v1.IndexDocumentRequest
	3, // 9: grpc_service.v1.SearchService.Search:output_type -> grpc_service.v1.SearchResponse
	6, // 10: grpc_service.v1.SearchService.GetStats:output_type -> grpc_service.v1.GetStatsResponse
	8, // 11: grpc_service.v1.SearchService.IndexDocument:output_type -> grpc_service.v1.IndexDocumentResponse
	9, // 12: grpc_service.v1.SearchService.BulkIndex:output_type -> grpc_service.v1.BulkIndexResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_grpc_service_v1_search_proto_init() }
func file_grpc_service_v1_search_proto_init() {
	if File_grpc_service_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_service_v1_search_proto_rawDesc), len(file_grpc_service_v1_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_service_v1_search_proto_goTypes,
		DependencyIndexes: file_grpc_service_v1_search_proto_depIdxs,
		EnumInfos:         file_grpc_service_v1_search_proto_enumTypes,
		MessageInfos:      file_grpc_service_v1_search_proto_msgTypes,
	}.Build()
	File_grpc_service_v1_search_proto = out.File
	file_grpc_service_v1_search_proto_goTypes = nil
	file_grpc_service_v1_search_proto_depIdxs = nil
}
